spring:
  datasource:
    url: jdbc:h2:mem:mato;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  data:
    redis:
      host: localhost
      port: 6379
      password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  jwt:
    secret-key: local-dev-secret-key-local-dev-secret-key

server:
  port: 8080
